version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: url
    versions:
    - 2.2.0
  - dependency-name: futures
    versions:
    - 0.3.12
    - 0.3.13
- package-ecosystem: cargo
  directory: "/vault-api"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: hyper
    versions:
    - "< 0.13, >= 0.12.a"
  - dependency-name: swagger
    versions:
    - 5.0.0
    - 5.1.0
