language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  include:
  - rust: "1.25.0"
    env: RUSTFMT=TRUE
    before_script:
    - rustup component add rustfmt-preview --toolchain 1.25.0
    script:
    - rustfmt -V
    - cargo fmt -- --write-mode diff
  - rust: nightly-2018-07-22
    env: CLIPPY=TRUE
    before_script:
    - rustup component add clippy-preview
    script:
    - cargo clippy -- -D warnings
  allow_failures:
  - rust: nightly
script:
  - cargo build
  - cargo test
  - cargo doc
branches:
  only:
    - staging
    - trying
    - master
